name: Django Deploy

on:
  workflow_run:
    workflows: ['Django CI']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: git pull
        working-directory: /home/rahul/mini_project
        run: |
          cd /home/rahul/mini_project
          git pull origin master
          source /home/rahul/mini_project/Backend/venv/bin/activate
          pip3 install -r /home/rahul/mini_project/Backend/requirements.txt
          python3 /home/rahul/mini_project/Backend/manage.py makemigrations
          python3 /home/rahul/mini_project/Backend/manage.py migrate
          python3 /home/rahul/mini_project/Backend/manage.py runserver 0.0.0.0:8000
