name: Django Deploy

on:
  workflow_run:
    workflows: ['Django CI']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: git pull
        working-directory: /home/rahul/mini_project
        run: |
          git pull
          source ./Backend/venv/bin/activate
          pip3 install -r ./Backend/requirements.txt
          python3 ./Backend/manage.py makemigrations
          python3 ./Backend/manage.py migrate
          python3 ./Backend/manage.py runserver 0.0.0.0:8000
